{{- if .Values.share }}
{{- range .Values.share }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "samba.name" $ }}-{{ .name }}
  namespace: {{ include "samba.namespace" $ }}
<<<<<<< Updated upstream
||||||| Stash base
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
=======
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
>>>>>>> Stashed changes
spec:
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName -}}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}