name: Lint & Release Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "charts/**"

jobs:
  lint:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Lint Helm Charts
        run: helm lint .

  release:
    name: Release Helm Chart
    needs: lint
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Extract Chart version
        id: chart
        run: |
          version=$(grep '^version:' ./Chart.yaml | awk '{print $2}')
          echo "chart_version=$version" >> "$GITHUB_OUTPUT"

      - name: Create Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ steps.chart.outputs.chart_version }}
          git push origin v${{ steps.chart.outputs.chart_version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.chart.outputs.chart_version }}
          name: Helm Chart Release ${{ steps.chart.outputs.chart_version }}
          files: ./**/*
